version: '3.1'

services:

  hg-dashboard-synapse-postgres:
    container_name: hg-dashboard-synapse-postgres
    hostname: hg-dashboard-synapse-postgres
    image: postgres:14
    restart: always
    volumes:
    - ./io/synapse/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
    - ./io/synapse/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: PG_P4SSW0RD_123
      POSTGRES_USER: synapse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse"]
      interval: 5s
      timeout: 5s
      retries: 5

  # See also https://hub.docker.com/r/mailhog/mailhog/
  hg-dashboard-smtp:
    container_name: hg-dashboard-smtp
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"  # disable saving logs
    ports:
    - "1025:1025" # smtp server
    - "8025:8025" # web ui

  # See also https://hub.docker.com/r/matrixdotorg/synapse/
  hg-dashboard-io:
    container_name: hg-dashboard-io
    image: matrixdotorg/synapse:latest
    restart: always
    volumes:
      - ./io/synapse/etc:/data
    ports:
    - "8008:8008" # matrix io server
    depends_on:
      - hg-dashboard-smtp
      - hg-dashboard-synapse-postgres

  # See also ./backend/README.md
  hg-dashboard-backend:
    container_name: hg-dashboard-backend
    restart: always
    build: ./backend
    environment:
      PORT: "3500"
      BACKEND_LOG_LEVEL: DEBUG
      BACKEND_URL: "http://0.0.0.0:3500"
      BACKEND_IO_SERVER: "http://app:p4sSw0rd123@hg-dashboard-io:8008"
      BACKEND_EMAIL_CONFIG: "smtp://hg-dashboard-smtp:1025"
      BACKEND_JWT_SECRET: "bwo4eay5ErCnqBV9zimo88UAmDxWTbN8"
    ports:
    - "3500:3500"
    depends_on:
    - hg-dashboard-smtp
    - hg-dashboard-io

  # See also ./frontend/README.md
  hg-dashboard-frontend-image:
    container_name: hg-dashboard-frontend-image
    image: "hg-dashboard-frontend-image:latest"
    build:
      context: "./frontend"
      args:
        DEFAULT_PUBLIC_URL: "http://localhost:3000"
    entrypoint: "sh -c"
    command: "exit 0"
    restart: "no"

  # See also https://hub.docker.com/_/nginx
  hg-dashboard-nginx:
    container_name: hg-dashboard-nginx
    restart: always
    image: "hg-dashboard-nginx:latest"
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        FRONTEND_IMAGE: "hg-dashboard-frontend-image:latest"
    ports:
      - "8080:8080"
    depends_on:
      - hg-dashboard-frontend-image
      - hg-dashboard-backend
    environment:
      NGINX_PORT: 8080
      NGINX_API_URL: "http://hg-dashboard-backend:3500"
